# Generated by Django 3.1 on 2020-08-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
